### ISSUE TITLE
removeFrom* fails with Neo4j-plugin 6.1.5, but works fine with 6.1.1

### ISSUE THREAD

**Issue by JulianRein** [grails/gorm-neo4j#66]
I have a simple one-to-many "hasMany" relationship in my domain class "Xxx". Adding children to it works, deleting them throws this (only in v. 6.1.5, works in 6.1.1):

> Caused by NoSuchMethodError: org.grails.datastore.mapping.model.types.Association.isOrphanRemoval()Z
->> 72 | adaptGraphUponRemove in org.grails.datastore.gorm.neo4j.collection.GraphAdapter

Code of domain class:

```
package xxxon

class Xxx {
    static mapping = {
        labels "xxx" //is lower-case in neo4j-DB
        //mapping not working, changed names in DB...
//         biochem name: 'BIOCHEMICAL' //ex. "citrate", "choline"
//         chemID name: 'CHEMICAL_ID'
//         yyyy name: 'YYYy_ID'
    }
    
    String biochem //ex. "citrate", "choline"
    int chemID
    String yyyy
    String sid
    
    static hasMany = [children:Xxx]

    static constraints = {
//     //for ordering
    sid()
    hmdb()
    biochem()
    chemID()
    }
    
    String toString() {
    return biochem+" (biochem.)" 
    }
}
```

Full error below:

> URI
    /xxx/removeChild/75274
Class
    java.lang.NoSuchMethodError
Message
    null

> Caused by
    org.grails.datastore.mapping.model.types.Association.isOrphanRemoval()Z
Around line 110 of grails-app/controllers/xxxon/XxxController.groovy
107:    def removeChild(){ 
108:    Xxx xxx=Xxx.get(params.id)
109://     xxx.removeFromChildren(Xxx.get(params.childID)) -> TRIED BOTH
110:    xxx.children.remove(Xxx.get(params.childID))
111:    xxx=xxx.save(flush:true,failOnError:true)
112:    redirect action:"edit",id: params.id
113:    

Trace

    Line | Method
->>  211 | invoke           in org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    188 | invoke           in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch       in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . .  in     ''
|    970 | processRequest   in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost . . . . . in     ''
|    846 | service          in     ''
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|   1149 | runWorker        in java.util.concurrent.ThreadPoolExecutor
|    624 | run . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run              in java.lang.Thread

Caused by NoSuchMethodError: org.grails.datastore.mapping.model.types.Association.isOrphanRemoval()Z
->>   72 | adaptGraphUponRemove in org.grails.datastore.gorm.neo4j.collection.GraphAdapter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     36 | adaptGraphUponRemove in org.grails.datastore.gorm.neo4j.collection.Neo4jPersistentSet
|     92 | remove . . . . . in     ''
|    110 | $tt__removeChild in XxxController.groovy
|     94 | doInTransaction  in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute          in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . .  in grails.gorm.transactions.GrailsTransactionTemplate
|    211 | invoke           in org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker
|    188 | invoke . . . . . in org.grails.core.DefaultGrailsControllerClass
|     90 | handle           in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . in org.springframework.web.servlet.DispatcherServlet
|    901 | doService        in     ''
|    970 | processRequest . in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost           in     ''
|    846 | service . . . .  in     ''
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|   1149 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor
|    624 | run              in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . . . .  in java.lang.Thread

**Comment by graemerocher** [comment]
Set your `gormVersion` property to `6.1.8.RELEASE` in gradle.properties

**Comment by JulianRein** [comment]
Thanks, works with that option. Is it more advisable to use the "newer" 6.0.13 version of the neo4j plugin for now?
